version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/rails_vue_portfolio
      - public-data:/rails_vue_portfolio/public
      - tmp-data:/rails_vue_portfolio/tmp
      - log-data:/rails_vue_portfolio/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/rails_vue_portfolio/public
      - tmp-data:/rails_vue_portfolio/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: